### PR TITLE
fix(rollup): order dependencies in correct way (#45)

### LINKED ISSUE #45: Config compiles dependencies in alphabetical order
**Describe the bug**
If no lib directory exists, config compiles packages in alphabetical order, which causes error if one of the dependencies, that should be compiled first, is at the end of alphabetical order.

**To Reproduce**
1. Remove lib directory from packages
2. Run rollup compile command

**Expected behavior**
All packages are compiled successfully in correct order

### PR DESCRIPTION
**Pull request by iamnurs**
closes #45

### CODE REVIEW

File: packages/rollup/src/graph/Graph.ts [hunk 1]
```diff
@@ -0,0 +1,82 @@
+export class Graph<T> {
+  // Making graph immutable requires complicated implementation and may cause optimization problems
+  // eslint-disable-next-line functional/prefer-readonly-type
+  private readonly graph: Map<T, Set<T>>;
+
+  public constructor() {
+    // eslint-disable-next-line functional/prefer-readonly-type
+    this.graph = new Map<T, Set<T>>();
```
Comment (olehan) [inline packages/rollup/src/graph/Graph.ts:8]: initialize on declare.

File: packages/rollup/src/index.ts [hunk 2]
```diff
@@ -1,2 +1,4 @@
 export * from './collect';
 export * from './fromWorkspaces';
+export * from './graph';
```
Comment (olehan) [inline packages/rollup/src/index.ts:3]: don't export internal modules

**Review by olehan — CHANGES_REQUESTED** [review]

**Review by olehan — APPROVED** [review]
